version: '3'

services:
  frontend:
    image: documyneacreastus2.azurecr.io/documyne-frontend
    env_file:
      - ./frontend/.env
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: web
    restart: always
    ports:
      - 80:80

  backend-core:
    image: documyneacreastus2.azurecr.io/documyne-backend
    env_file:
      - ./backend/.env
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: backend-core
    restart: always
    volumes:
      - ./backend/:/code/
    depends_on:
      - redis
      - worker
    ports:
      - 5050:5050
    
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - 6379:6379
  
  worker:
    image: documyneacreastus2.azurecr.io/worker:latest
    env_file:
      - ./backend/.env
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: worker
    command: celery -A celery_worker worker -l info
    restart: always
    depends_on:
      - redis
    volumes:
      - ./backend/:/code/    
    
  flower:
    image: documyneacreastus2.azurecr.io/flower:latest
    env_file:
      - ./backend/.env
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: flower
    command: celery -A celery_worker flower -l info --port=5555
    restart: always
    volumes:
      - ./backend/:/code/
    depends_on:
      - redis
      - worker
    ports:
      - 5555:5555