version: '3.8'

services:
  frontend:
    image: documyneacreastus2.azurecr.io/documyne-frontend:latest
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: web
    restart: always
    ports:
      - 80:80
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 0.5GB
        reservations:
          cpus: '0.25'
          memory: 0.2GB

  backend-core:
    image: documyneacreastus2.azurecr.io/documyne-backend:latest
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: backend-core
    restart: always
    volumes:
      - backend-storage:/code/
    # depends_on:
    #   - redis
    #   - worker
    ports:
      - 5050:5050
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 0.5GB
        reservations:
          cpus: '0.25'
          memory: 0.2GB

  redis:
    image: mcr.microsoft.com/oss/bitnami/redis:6.0.8
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 0.5GB
        reservations:
          cpus: '0.25'
          memory: 0.2GB

  
  worker:
    image: documyneacreastus2.azurecr.io/worker:latest
    env_file:
      - ./backend/.env
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: worker
    command: celery -A celery_worker worker -l info
    restart: always
    depends_on:
      - redis
    volumes:
      - backend-storage:/code/
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 0.5GB
        reservations:
          cpus: '0.25'
          memory: 0.2GB

    
  # flower:
  #   image: documyneacreastus2.azurecr.io/flower:latest
  #   env_file:
  #     - ./backend/.env
  #   build:
  #     context: backend
  #     dockerfile: Dockerfile
  #   container_name: flower
  #   command: celery -A celery_worker flower -l info --port=5555
  #   restart: always
  #   volumes:
  #     - backend-storage:/code/
  #   depends_on:
  #     - redis
  #     - worker
  #   ports:
  #     - 5555:5555
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.50'
  #         memory: 0.5GB
  #       reservations:
  #         cpus: '0.25'
  #         memory: 0.2GB

volumes:
  backend-storage:
    driver: azure_file
    driver_opts:
      share_name: documyne-be-file-share
      storage_account_name: documynestorageaccount3
      storage_account_key: QuG+LqdR4wQottyevL3OVzE050TilOe0NUHyE4xr+2/d7iaimAy0VYaoWfj0Zojkwf/RlqPn0X39+AStvtElCA==